[build]
  command = "npm run build:ssr"
  publish = "dist/make_tweet/browser"
#  functions = "functions"
  functions = "dist/make_tweet/server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200